print("Hello, AtufaBanu Shaikh")
print("Atufa is here")
print("This is New Line")
print("This is Second Line")
print("This is Third Line")
print("Ay Gundi")
print("Kya hai ?")
print("2 paher h 😅")
print("barabar pata hai mennu aayi samajh and pich pich 🤨🤨🤨")
print("pichpich ni hoa h vo muaah muuah ya pucch pucch hota h 😅")
print("This is 11th line")